data-path="/usr/app/data"

bootnodes=["enode://497a10b16ff38dab1e25d2a362a820367eb0d0e2d22590060690566722690390d8c3e89f9047dbc677fc4e4083660567658490e608c61fdf7d916f31faadcd75@127.0.0.1:30304"]

rpc-http-enabled=true
rpc-http-api=["ETH", "NET", "IBFT"]
rpc-http-port=8547

p2p-port=30305

permissions-nodes-config-file-enabled=true

permissions-accounts-config-file-enabled=true

host-allowlist=["*"]

rpc-http-cors-origins=["all"]

genesis-file="/usr/app/genesis.json"

min-gas-price=0